config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pans
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to posts_path, notice: "Nie jesteś uprawniony do edycji tego postu" if @post.nil?

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data- 6 toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to 'Gallery', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Strona główna', root_path %></li>
        <li><%= link_to 'O mnie', home_about_path %></li>
        <li><%= link_to 'Lista postów', posts_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to 'Edycja profilu', edit_user_registration_path %></li>
          <li><%= link_to 'Nowy Post', new_post_path %></li>
          <li><%= link_to 'Wylogowanie', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Logowanie", new_user_session_path %></li>
          <li><%= link_to "Rejestracja", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="jumbotron">
  <h1>O mnie...</h1>
  <p>Nazywam się Benny i tworzę aplikację gallery</p>
  <%= link_to 'O mnie', home_about_path, class: 'btn btn-warning btn-lg'%>
  <%= link_to 'Strona główna', root_path, class: 'btn btn-primary btn-lg'%>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Witaj w mojej aplikacji!</h1>
  <p>Niebawem dodam więcej funkcji...</p>
  <%= link_to 'O mnie', home_about_path, class: 'btn btn-warning'%>
  <%= link_to 'Strona główna', root_path, class: 'btn btn-primary'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description, "Opis"  %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Utwórz post", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edycja Postu</h1>

<%= render 'form', post: @post %>

<%= link_to 'Wyświetl', @post %> |
<%= link_to 'Wstecz', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="panel-heading"><h2>Lista postów</h2></div>
    <div class="panel-body">

<table>
  <thead>
    <tr>
      <th>Opis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.description %></td>
        <td><%= link_to 'Wyświetl', post %></td>
        <% if post.user == current_user %>
          <td><%= link_to 'Edycja', edit_post_path(post) %></td>
          <td><%= link_to 'Usuń', post, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

<div class="panel-footer"><%= link_to 'Nowy Post', new_post_path, class: 'btn btn-primary' %></div>
</div>

app/views/posts/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2>Nowy Post</h2></div>
    <div class="panel-body">

</div>

<div class="panel-footer"><%= render 'form', post: @post %>
<%= link_to 'Wstecz', posts_path %></div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Opis:</strong>
  <%= @post.description %>
</p>
<% if @post.user == current_user %>
  <%= link_to 'Edycja', edit_post_path(@post) %>
<% end %>
<%= link_to 'Wstecz', posts_path %>